version: '3.8'

# ===============================================
# mysql -> 3306
# redis -> 1002
# backend -> 1003
# frontend -> 1004
# minio -> address@1005 | web@1006
# nginx -> [1007/tcp -> 0.0.0.0:1007]
# nginx#minio -> [1008/tcp/ws -> 0.0.0.0:1008]
# ===============================================

services:

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "1002:6379"
    environment:
      TZ: "Asia/Shanghai"
    command: ["redis-server", "--requirepass", "fluxsync", "--notify-keyspace-events", "Ex"]
    networks:
      - fluxsync-networks

  mysql:
    container_name: mysql
    image: fluxsync/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fluxsync
      MYSQL_DATABASE: fluxsync
      TZ: "Asia/Shanghai"
    networks:
      - fluxsync-networks

  backend:
    container_name: backend
    image: fluxsync/backend
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      PORT: "1003"
    networks:
      - fluxsync-networks

  frontend:
    container_name: frontend
    image: fluxsync/frontend
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    networks:
      - fluxsync-networks

  minio:
    container_name: minio
    image: minio/minio
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: fluxsync
      MINIO_SERVER_URL: http://host.docker.internal:1008
      MINIO_BROWSER_REDIRECT_URL: http://host.docker.internal:1008
      MINIO_PROMETHEUS_AUTH_TYPE: public
    command: server /data --address ":1005" --console-address ":1006"
    networks:
      - fluxsync-networks

  nginx:
    container_name: nginx
    image: fluxsync/nginx
    restart: always
    ports:
      - "1007:1007"
      - "1008:1008"
    environment:
      TZ: "Asia/Shanghai"
    networks:
      - fluxsync-networks


networks:
  fluxsync-networks:
    driver: bridge
